backend/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get root to: 'toppages#index'

  resources :users, only: %i[show edit update]

  resources :subscribes, only: %i[create destroy]
  resources :favorites, only: %i[create destroy]

  get 'books', to: 'books#new'
  get 'books/:isbn', to: 'books#show', as: 'book'
  get 'books/:isbn/reviews/new', to: 'reviews#new', as: 'review_new'
  get 'subscribe-ranking', to: 'books#ranking'
  get 'review-ranking', to: 'books#review_ranking'

  get 'howto', to: 'toppages#howto'

  resources :reviews
  get 'reviews/index/:id', to: 'reviews#index', as: 'review_index'
  get 'reviews/error', to: 'reviews#error'

  resources :reviewfavorites, only: %i[create destroy]
  get 'newlys/download', to: 'newlys#download'
  get 'newlys', to: 'newlys#search'
  get 'favnews', to: 'newlys#newfav'

  # API routes
  get 'v1/ranking/subs', to: 'books#api_subs_ranking'
  get 'v1/ranking/review', to: 'books#api_review_ranking'
  get 'v1/books', to: 'books#api_new'

  namespace :v1 do
    mount_devise_token_auth_for 'User', at: 'auth', controllers: {
      confirmations:  'overrides/confirmations'
    }
  end
end

backend/app/controllers/reviews_controller.rb
# frozen_string_literal: true

class ReviewsController < ApplicationController
  before_action :correct_user, only: %i[edit destroy]
  before_action :require_sign_in

  def index
    @reviews = Review.where(book_id: params[:id]).page(params[:page]).per(10)
  end

  def show
    @review = Review.find(params[:id])
    @review_book = @review.book
    @user = @review.user
  end

  def new
    @review = Review.new
    @book = Book.find_by(isbn: params[:isbn])
  end

  def create
    @review = Review.new(new_review_params(params[:book_id]))
    @book = Book.find(params[:book_id])
    if @review.save
      flash[:success] = 'レビューが正常に投稿されました'
      redirect_to review_path(@review)
    else
      flash.now[:danger] = 'レビューが投稿されませんでした'
      render new_review_path
    end
  end

  def edit
    if current_user == Review.find(params[:id]).user
      @review = Review.find(params[:id])
    else
      redirect_to review_path(Review.find(params[:id]))
    end
  end

  def update
    @review = Review.find(params[:id])
    if @review.update(review_params)
      flash[:success] = 'レビューは正常に更新されました'
      redirect_to @review
    else
      flash.now[:danger] = 'レビューは更新されませんでした'
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @book = Book.find(@review.book_id)
    @review.destroy
    flash[:success] = 'レビューは正常に削除されました'
    redirect_to book_path(@book.isbn)
  end

  def error; end

  private

  def new_review_params(book_id)
    strong_params = params.require(:review).permit(:head, :content, :point)
    strong_params[:user_id] = current_user.id
    strong_params[:book_id] = book_id
    strong_params
  end

  def review_params
    params.require(:review).permit(:head, :content, :point)
  end

  def require_sign_in
    return if user_signed_in?

    flash[:warning] = 'このページをみるにはログインが必要です。'
    redirect_to user_session_path
  end

  def correct_user
    return unless current_user.admin == false

    @review = current_user.reviews.find(params[:id])
    redirect_to root_path if current_user != @review.user
  end
end

backend/app/views/reviews/_review_card.html.erb
  <% review_book = Book.find(review.book_id) %>
  <div class="card w-80 m-4">
    
    <div class="card-body">
      <h5 class="card-title mark"><%= link_to review.head, review_path(review.id), class: "text-decoration-none text-dark" %></h5>
      <div class="row mb-3">
        <div class="col-lg-2 col-md-3 text-center">
          <img src="<%= review_book.image_url %>" style="width:auto; height:175px; max-width:125px;">
        </div>
        <div class="col-lg-10 col-md-9 ">
          <h6><%= link_to review_book.title, book_path(review_book.isbn), class: "card-subtitle mb-2 text-muted" %></h6>
          <h6 class="card-subtitle mb-2 text-muted"><%= review.created_at.strftime("%Y年%m月%d日%H時%m分") %> に投稿</h6>
          <h6 class="card-subtitle mb-2 text-muted">投稿者:<%= link_to User.find(review.user_id).name, user_path(review.user_id) %></h6>
          <h6 class="card-subtitle mb-2 text-muted">評価:<%= review.point %></h6>
          <p class="card-text"><%= simple_format(h(review.content)) %></p>
        </div>
      </div>
      <div class="reviewfavorite_zone_<%= review.id %>">
        <%= render 'reviewfavorites/review_fav_button', review: review %>
      </div>
    </div>
  </div>

backend/app/views/reviews/_review_create_button.html.erb
<% if Book.find(book.id).reviewuser.include?(current_user) %>
  <btn class="btn btn-info disabled">既にレビューを書いています</btn>
<% else %>
  <%= link_to 'レビューを書く', review_new_path(book.isbn), class:"btn btn-info" %>
<% end %>

backend/app/views/reviews/edit.html.erb
<% if @review.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg.sub("Head","レビュー名").sub("Content","レビュー本文") %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<h1>レビュー編集ページ</h1>

<%= form_with(model: @review, local: true) do |f| %>


  <%= hidden_field_tag :book_id, @review.book.id %>
  
  <div class="m-4">
    <%= f.label :head, 'レビュー名' %>
    <%= f.text_field :head, class: 'form-control' %>
  </div>
  
  <div class="m-4">
    <%= f.label :content, 'レビュー本文' %>
    <%= f.text_area :content, class: 'form-control', size: '20x10' %>
  </div class="m-2">
  
  <div class="m-4">
    <%= f.label :point, '評価（0~5で評価、小数可）' %>
    <%= f.number_field :point, step: 0.1, min: 0, max: 5, value: 5, class: 'form-control' %>
  </div>
  
  <%= f.submit '送信する', class: 'btn btn-primary m-4'%>
<% end %>

<%= link_to '詳細ページに戻る', @review %>

backend/app/views/reviews/error.html.erb
<% if @review.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

backend/app/views/reviews/index.html.erb
<% @reviews.each do |review| %>
  <%= render 'review_card', review:review %>
<% end %>
<%= paginate @reviews %>

backend/app/views/reviews/new.html.erb
<% if @review.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg.sub("Head","レビュー名").sub("Content","レビュー本文") %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<h2>レビュー投稿フォーム</h2>


<%= link_to @book.title, book_path(@book.isbn) %>のレビューを書きます。
<%= form_with(model: @review, local: true) do |f| %>
  <%= hidden_field_tag :book_id, @book.id %>
  
  <div class="m-4">
    <%= f.label :head, 'レビュー名（20文字以内）' %>
    <%= f.text_field :head, class: 'form-control' %>
  </div>
  
  <div class="m-4">
    <%= f.label :content, 'レビュー本文（2000文字以内）' %>
    <%= f.text_area :content, class: 'form-control', size: '20x10' %>
    現在の文字数：<span class="count">0</span>文字
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
    <script type="text/javascript">
    $(function(){
        $('textarea').bind('keydown keyup keypress change',function(){
            var thisValueLength = $(this).val().length;
            $('.count').html(thisValueLength);
        });
    });
    </script>
  </div class="m-2">
  
  <div class="m-4">
    <%= f.label :point, '評価（0~5で評価、小数可）' %>
    <%= f.number_field :point, step: 0.1, min: 0, max: 5, value: 5, class: 'form-control' %>
  </div>
  
  <%= f.submit '送信する', class: 'btn btn-primary m-4'%>
<% end %>

backend/app/views/reviews/show.html.erb
<div class="card w-80 m-4">
  <div class="card-body">
    <h5 class="card-title"><%= @review.head %></h5>
    <div class="row mb-3">
      <div class="col-lg-2 col-md-3 text-center">
        <img src="<%= @review_book.image_url %>" style="width:auto; height:175px; max-width:125px;">
      </div>
      <div class="col-lg-10 col-md-9 ">
        <h6><%= link_to @review_book.title, book_path(@review_book.isbn), class: "card-subtitle mb-2 text-muted" %></h6>

        <h6 class="card-subtitle mb-2 text-muted"><%= @review.created_at.strftime("%Y年%m月%d日%H時%m分") %>に投稿</h6>
        <h6 class="card-subtitle mb-2 text-muted">投稿者:<%= link_to @user.name, user_path(@user) %></h6>
        <h6 class="card-subtitle mb-2 text-muted">評価:<%= @review.point %></h6>
        <% if @current_user == @user %>
        <%= link_to '編集する', edit_review_path(@review) %>
        <% end %>
        <% if @current_user == @user || @current_user.admin? %>
        <%= link_to '削除する', @review, method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %>
        <% end %>
        <p class="card-text"><%= simple_format(h(@review.content)) %></p>
      </div>
    </div>
  </div>
</div>