backend/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get root to: 'toppages#index'

  resources :users, only: %i[show edit update]

  resources :subscribes, only: %i[create destroy]
  resources :favorites, only: %i[create destroy]

  get 'books', to: 'books#new'
  get 'books/:isbn', to: 'books#show', as: 'book'
  get 'books/:isbn/reviews/new', to: 'reviews#new', as: 'review_new'
  get 'subscribe-ranking', to: 'books#ranking'
  get 'review-ranking', to: 'books#review_ranking'

  get 'howto', to: 'toppages#howto'

  resources :reviews
  get 'reviews/index/:id', to: 'reviews#index', as: 'review_index'
  get 'reviews/error', to: 'reviews#error'

  resources :reviewfavorites, only: %i[create destroy]
  get 'newlys/download', to: 'newlys#download'
  get 'newlys', to: 'newlys#search'
  get 'favnews', to: 'newlys#newfav'

  # API routes
  get 'v1/ranking/subs', to: 'books#api_subs_ranking'
  get 'v1/ranking/review', to: 'books#api_review_ranking'
  get 'v1/books', to: 'books#api_new'

  namespace :v1 do
    mount_devise_token_auth_for 'User', at: 'auth', controllers: {
      confirmations:  'overrides/confirmations'
    }
  end
end

backend/app/models/book.rb
# frozen_string_literal: true

class Book < ApplicationRecord
  before_save :set_series
  validates :title, presence: true
  validate :validate_title
  validates :author, presence: false
  validates :publisherName, presence: true
  validates :url, presence: true, format: /\A#{URI.regexp(%w[http https])}\z/
  validates :salesDate, presence: true
  validates :isbn, presence: true, length: { is: 13 }
  validates :image_url, format: /\A#{URI.regexp(%w[http https])}\z/
  validates :series, presence: true
  validates :salesint, presence: true

  has_many :subscribes, foreign_key: 'book_id', dependent: :destroy
  has_many :users, through: :subscribes

  has_many :reviews, foreign_key: 'book_id', dependent: :destroy
  has_many :reviewuser, through: :reviews, source: :user

  has_many :favorites, foreign_key: 'book_id', dependent: :destroy
  has_many :favusers, through: :favorites, source: :user

  belongs_to :bookseries, optional: true

  def count_subs
    count = Book.joins(:subscribes).group(:book_id).count[id]
    count || 0
  end

  def count_favs
    count = Book.joins(:favorites).group(:book_id).count[id]
    count || 0
  end

  def get_review_average_point
    self.reviews.average(:point)
  end

  private

  def set_series
    return unless Bookseries.find_by(title: series).nil?

    bookseries = Bookseries.new(title: series, publisher: publisherName)
    bookseries.save
  end

  def validate_title
    errors.add(:title, '適正のない書籍は登録出来ません') if title =~ /コミックカレンダー|(巻|冊|BOX)セット/
  end
end

backend/app/controllers/books_controller.rb
# frozen_string_literal: true

class BooksController < ApplicationController
  # before_action :require_sign_in
  def new
    @page = params[:pageselect].presence || 1
    return unless params[:title].present?

    view_context.search_books(params[:title], params[:sortselect], @page)
    @no_results = '漫画は見つかりませんでした。' if @books.blank?
  end

  def api_new
    @books = []

    sort = params[:sort].presence || 'standard'
    page = params[:pageselect].presence || 1

    return unless params[:title].present?

    view_context.search_books(params[:title], sort, page)
    unless @books.blank?
      render json: {
        success: true,
        data: @books.as_json
      }
    else
      render json: {
        success: false
      }, status: 401
    end
  end

  def show
    @book = Book.find_or_initialize_by(isbn: params[:isbn])
    return if @book.persisted?

    @book = Book.new(view_context.search_isbn(@book.isbn))
    @book.save
  end

  def ranking
    book_subs_ids = Hash[Subscribe.group(:book_id).count.sort_by { |_, v| -v }].keys
    @book_ranking = Book.where(id: book_subs_ids).order("FIELD(id, #{book_subs_ids.join(',')})").limit(30)
  end

  def api_subs_ranking
    result = []
    for book in Book.all do
      book_hash = book.attributes
      book_hash["subs"] = book.count_subs
      result.push(book_hash)
    end
    render json: { status: 'SUCCESS', message: 'Loaded subs rankings', data: result }
  end

  def review_ranking
    @book_review_average = Book.joins(:reviews).group(:book_id).average(:point)
    book_review_ids = Hash[@book_review_average.sort_by { |_, v| -v }].keys
    @review_ranking = Book.where(id: book_review_ids).order("FIELD(id, #{book_review_ids.join(',')})").limit(30)
  end

  def api_review_ranking
    result = []
    for book in Book.all do
      book_hash = book.attributes
      book_hash["point"] = book.get_review_average_point
      result.push(book_hash)
    end
    render json: { status: 'SUCCESS', message: 'Loaded review rankings', data: result }
  end

  private

  def require_sign_in
    return if user_signed_in?

    flash[:warning] = 'このページをみるにはログインが必要です。'
    redirect_to user_session_path
  end
end

backend/app/helpers/books_helper.rb
# frozen_string_literal: true

module BooksHelper
  def search_books(title, sort, page)
    results = RakutenWebService::Books::Book.search(
      title: title,
      booksGenreId: '001001',
      outOfStockFlag: '1',
      sort: sort,
      page: page
    )
    check_results(results)
  end

  def check_results(results)
    results.each do |result|
      book = Book.new(read(result))
      @books << book unless book.title =~ /カレンダー|(巻|冊|BOX)セット/
    end
    @books
  end

  def search_isbn(isbn)
    results = RakutenWebService::Books::Book.search(
      isbn: isbn,
      outOfStockFlag: '1'
    )
    read(results.first)
  end

  def read(result)
    { title: result['title'],
      author: result['author'],
      publisherName: result['publisherName'],
      url: result['itemUrl'],
      salesDate: result['salesDate'],
      isbn: result['isbn'],
      image_url: result['mediumImageUrl'].gsub('?_ex=120x120', '?_ex=350x350'),
      series: series_create(result['title']),
      salesint: result['salesDate'].gsub(/年|月|日/, '').to_i }
  end

  def series_create(title)
    title.sub(
      /（.*|\(.*|\p{blank}\d.*|公式ファンブック.*|外伝.*|\p{blank}巻ノ.*/, ''
    )
         .gsub(
           /\p{blank}/, ''
         )
         .gsub(/：/, ':')
         .gsub(/トーキョーグール/, '')
         .gsub(/\!/, '！')
  end

  def publisher_name_array
    ['集英社', '小学館', '講談社', '竹書房', '白泉社', '新潮社', '双葉社', '宙出版', '秋田書店', '少年画報社', 'KADOKAWA', 'ハーパーコリンズ・ジャパン']
  end

  def change_isbn(isbn13)
    body = isbn13[3..-2]
    sum = body.each_char.map.with_index { |a, b| a.to_i * (10 - b) }.sum
    mod = sum % 11
    raw_digit = 11 - mod
    digit = case raw_digit
            when 11 then '0'
            when 10 then 'X'
            else raw_digit.to_s
            end
    "#{body}#{digit}"
  end
end

backend/app/views/books/_book_card_small.html.erb

    <div class="col-lg-3">
      <div class="card text-center rounded-0 " style="height: 350px; ">
        <div class="p-0">
          <%= link_to book_path(book.isbn), target: "_blank" do %>
            <img src="<%= book.image_url %>" style="width:auto; height:350px; max-width:250px;">
          <% end %>
        </div>
      </div>
      <div class="card mb-4 rounded-0" style="height:350px;">
        <div class="row no-gutters">
          <div class="card-body w-100" style="height:350px;">
            <div style="height: 185px;">
              <p class="card-text mark"><%= book.publisherName %></p>
              <h5 class="card-title"><%= link_to book.title, book_path(book.isbn), style: 'text-decoration:none;' %></h5>
              <h6 class="card-subtitle mb-2 text-muted"><%= book.author %></h6>
              <p class="card-text">発売日 <%= book.salesDate %></p>
            </div>
              <%= render 'subscribes/sub_button', isbn: book.isbn %>
              <%= render 'favorites/fav_button', isbn: book.isbn %>
              <div class="mt-2">
                <a href="<%= book.url %>" class="card-link btn-sm btn-dark" target="_blank">楽天</a>
                <% amazonurl = "http://www.amazon.co.jp/dp/#{change_isbn(book.isbn)}" %>
                <a href="<%= amazonurl %>" class="card-link btn-sm btn-dark ml-1" target="_blank">Amazon</a>
                <% unless book.series.nil? %>
                  <%= link_to "検索", {controller: "books", action: "new", title: book.series, sortselect: "+releaseDate"}, class: "card-link btn-sm btn-light border ml-1" %>
                <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>

backend/app/views/books/_books_card_small.html.erb
<div class="row">
  <% if books.present? %>
    <% books.each do |book| %>
    <div class="col-xl-3 col-lg-4 col-md-6">
      <div class="card text-center rounded-0 border-bottom-0 pt-1" style="height: 370px; ">
        <div class="p-0">
          <%= link_to book_path(book.isbn), target: "_blank" do %>
            <img src="<%= book.image_url %>" style="width:auto; height:350px; max-width:250px;">
          <% end %>
        </div>
      </div>
      <div class="card mb-4 rounded-0 border-top-0" style="height:350px;">
        <div class="row no-gutters">
          <div class="card-body w-100" style="height:350px;">
            <div style="height: 185px;">
              <p class="card-text mark"><%= book.publisherName %></p>
              <h5 class="card-title"><%= link_to book.title, book_path(book.isbn), style: 'text-decoration:none;' %></h5>
              <h6 class="card-subtitle mb-2 text-muted"><%= book.author %></h6>
              <p class="card-text">発売日 <%= book.salesDate %></p>
            </div>
              <div class="subscribe_book_zone_<%= book.isbn %>">
                <%= render 'subscribes/sub_button', isbn: book.isbn %>
              </div>
              <div class="favorite_book_zone_<%= book.isbn %>">
                <%= render 'favorites/fav_button', isbn: book.isbn %>
              </div>
              <div class="mt-2">
                <a href="<%= book.url %>" class="card-link btn-sm btn-dark" target="_blank">楽天</a>
                <% amazonurl = "http://www.amazon.co.jp/dp/#{change_isbn(book.isbn)}" %>
                <a href="<%= amazonurl %>" class="card-link btn-sm btn-dark ml-1" target="_blank">Amazon</a>
                <% unless book.series.nil? %>
                  <%= link_to "検索", {controller: "books", action: "new", title: book.series, sortselect: "+releaseDate"}, class: "card-link btn-sm btn-light border ml-1" %>
                <% end %>
              </div>
          </div>
        </div>
      </div>
    </div>
    
    <% end %>
<% end %>
</div>

backend/app/views/books/_books_list.html.erb
<% if books.present? %>
  <%= books.count %>件
  <ul class="list-group mb-2" >
  <li class="list-group-item row list-group-item-success" style="width:max">
    <div class="row">
        <div class="col-lg-6">タイトル</div>
        <div class="col-lg-2">作者名</div>
        <div class="col-lg-2">発売日</div>
        <div class="col-lg-2">リンク</div>
      </div>
  </li>
  <% books.each do |book| %>
    <li class="list-group-item row" style="width:max">
      <div class="row">
        <div class="col-lg-6"><%= link_to book.title, book_path(book.isbn), class: 'text-decoration-none text-body' %></div>
        <div class="col-lg-2"><%= book.author %></div>
        <div class="col-lg-2"><%= book.salesDate %></div>
        <div class="col-lg-2">
          <a href="<%= book.url %>" class="card-link btn-sm btn-dark" target="_blank">楽天</a>
          <% amazonurl = "http://www.amazon.co.jp/dp/#{change_isbn(book.isbn)}" %>
          <a href="<%= amazonurl %>" class="card-link btn-sm btn-dark ml-1" target="_blank">Amazon</a>
        </div>
      </div>
    </li>
  <% end %>
  </ul>
<% end %>

backend/app/views/books/_books_modal_list.html.erb
<% if books.present? %>
  合計<%= books.count %>冊
  <ul class="list-group mb-2" >
  <li class="list-group-item row list-group-item-primary" style="width:max">
    <div class="row">
      <div class="col-lg-8">タイトル</div>
      <div class="col-lg-4">発売日</div>
    </div>
  </li>
  <% books.each do |book| %>
    <li class="list-group-item row" style="width:max">
      <div class="row">
        <div class="col-lg-8"><%= link_to book.title, book_path(book.isbn), target: :_blank, class: 'text-decoration-none text-body' %></div>
        <div class="col-lg-4"><%= book.salesDate %></div>
      </div>
    </li>
  <% end %>
  </ul>
<% end %>

backend/app/views/books/_ranking_books_card.html.erb
<div class="col-lg-4 col-md-6">
  <div class="card text-center rounded-0 border-bottom-0 " style="height: 440px; ">
    <div class="p-0">
      <h4 class="mt-2"><%= @rank %>位</h4>
      <h6 class="text-muted">登録数 <%= book.count_subs %></h6>
      <%= link_to book_path(book.isbn), target: "_blank" do %>
        <img src="<%= book.image_url %>" style="width:auto; height:370px; max-width:250px;">
      <% end %>
    </div>
  </div>
  <div class="card mb-4 rounded-0 border-top-0">
    <div class="row no-gutters">
      <div class="card-body w-100">
          <h5 class="card-title"><%= link_to book.title, book_path(book.isbn), style: 'text-decoration:none;' %></h5>
          <h6 class="card-subtitle mb-2 text-muted"><%= book.author %></h6>
          <div class="subscribe_book_zone_<%= book.isbn %>">
            <%= render 'subscribes/sub_button', isbn: book.isbn %>
          </div>
          <div class="favorite_book_zone_<%= book.isbn %>">
            <%= render 'favorites/fav_button', isbn: book.isbn %>
          </div>
          <div class="mt-2">
            <a href="<%= book.url %>" class="card-link btn-sm btn-dark" target="_blank">楽天</a>
            <% amazonurl = "http://www.amazon.co.jp/dp/#{change_isbn(book.isbn)}" %>
            <a href="<%= amazonurl %>" class="card-link btn-sm btn-dark ml-1" target="_blank">Amazon</a>
            <% unless book.series.nil? %>
              <%= link_to "検索", {controller: "books", action: "new", title: book.series, sortselect: "+releaseDate"}, class: "card-link btn-sm btn-light border ml-1" %>
            <% end %>
          </div>
      </div>
    </div>
  </div>
</div>
    

backend/app/views/books/_review_ranking_books_card.html.erb
<div class="col-lg-4 col-md-6">
  <div class="card text-center rounded-0 border-bottom-0 " style="height: 440px; ">
    <div class="p-0">
      <h4 class="mt-2"><%= @rank %>位</h4>
      <% @point = BigDecimal(@book_review_average[book.id].to_s).floor(2).to_f %>
      <h6 class="text-muted">平均評価 <%= @point %></h6>
      <%= link_to book_path(book.isbn), target: "_blank" do %>
        <img src="<%= book.image_url %>" style="width:auto; height:370px; max-width:250px;">
      <% end %>
    </div>
  </div>
  <div class="card mb-4 rounded-0 border-top-0">
    <div class="row no-gutters">
      <div class="card-body w-100">
          <h5 class="card-title"><%= link_to book.title, book_path(book.isbn), style: 'text-decoration:none;' %></h5>
          <h6 class="card-subtitle mb-2 text-muted"><%= book.author %></h6>
          <div class="subscribe_book_zone_<%= book.isbn %>">
            <%= render 'subscribes/sub_button', isbn: book.isbn %>
          </div>
          <div class="favorite_book_zone_<%= book.isbn %>">
            <%= render 'favorites/fav_button', isbn: book.isbn %>
          </div>
          <div class="mt-2">
            <a href="<%= book.url %>" class="card-link btn-sm btn-dark" target="_blank">楽天</a>
            <% amazonurl = "http://www.amazon.co.jp/dp/#{change_isbn(book.isbn)}" %>
            <a href="<%= amazonurl %>" class="card-link btn-sm btn-dark ml-1" target="_blank">Amazon</a>
            <% unless book.series.nil? %>
              <%= link_to "検索", {controller: "books", action: "new", title: book.series, sortselect: "+releaseDate"}, class: "card-link btn-sm btn-light border ml-1" %>
            <% end %>
          </div>
      </div>
    </div>
  </div>
</div>
    

backend/app/views/books/new.html.erb
<h1 class="title_comicfarm_big text-center">ComicFarm</h1>
<div class="mark mb-3">
  ここでは好きな漫画をタイトルで検索することが出来ます。<br>
  また、ソート機能によって並び順を変更することも可能です。
</div>
<div class="mb-5">
  <%= form_with url: books_path, method: :get, local: true do |f| %>
    <div class="form-group row">
      <%= f.label :title, 'タイトル', class: "col-lg-2 pt-1" %>
      <%= f.text_field "title", value: params[:title], class: 'form-control mb-2 col-lg-10' %>
      <%= f.label :sortselect, 'ソート設定', class: "col-lg-2 pt-1" %>
      <% @sort_array = [{id: "+releaseDate", name: "古い順"}, {id: "-releaseDate", name: "新しい順"}, {id: "sales", name: "売れている順"}] %>
      <%= f.select :sortselect, options_for_select(@sort_array.map{|c|[c[:name], c[:id], {}]},params[:sortselect]), {}, class: 'form-control mb-2 col-lg-10' %>
      <%= f.label :pageselect, 'ページ指定', class: "col-lg-2 pt-1" do %>
        <span id="hoge" class="" data-toggle="popover" title="ページ指定とは？" data-content="この検索は楽天APIを用いているので、1ページあたり30冊までしか表示できません。なので数の多い漫画を検索するときはページ数を指定することができます。">
        ページ指定
        </span>
      <% end %>
      
      <%= f.number_field :pageselect, step: 1, min: 1, max: 100, value: @page, class: 'form-control mb-2 col-lg-10' %>
    </div>
    <div class="form-group row">
      <%= f.submit "検索", class:'btn btn-success btn-block mt-4' %>
    </div>
    <script>
      $(function() {
        $('#hoge').popover({
          trigger: 'hover',
        });
      });
    </script>
  <% end %>
</div>
<%= @no_results %>
<%= render 'books_card_small', books: @books %>

backend/app/views/books/ranking.html.erb
<h2 class="pb-4"><i class="fa fa-plus"></i> 登録数ランキング</h2>
<div class="mark mb-5">
  <p class="pt-3">こちらのランキングは各ユーザーの所持漫画情報を元に作成したものです。</p>
</div>
<div class="row">
  <% if @book_ranking.present? %>
  <% @rank = 1 %>
  <% @book_ranking.each do |book| %>
    <%= render 'ranking_books_card', book: book, test: "a" %>
    <% @rank+=1 %>
  <% end %>
  <% end %>
</div>

backend/app/views/books/review_ranking.html.erb
<h2 class="pb-4"><i class="fa fa-thumbs-up"></i> 高評価ランキング</h2>
<div class="mark mb-5">
  <p class="pt-3">こちらのランキングはユーザーが投稿したレビューを元に平均評価を割り出し、それを順位づけしたものです。</p>
</div>
<div class="row">
<% if @review_ranking.present? %>
  <% @rank = 1 %>
  <% @review_ranking.each do |book| %>
    <%= render 'review_ranking_books_card', book: book, test: "a" %>
    <% @rank+=1 %>
  <% end %>
<% end %>
</div>

backend/app/views/books/show.html.erb
<div class="card mb-4 h-350px">
  <div class="row no-gutters">
    <div class="col-md-3 p-1">
        <img src="<%= @book.image_url %>" style="width:auto; height:350px; max-width:250px;">
    </div>
    <div class="col-md-9">
      <div class="card-body p-3">
        <p class="card-text mark"><%= @book.publisherName %></p>
        <h5 class="card-title"><%= @book.title %></h5>
        <h6 class="card-subtitle mb-2 text-muted"><%= @book.author %></h6>
        <div class="row pl-3">
          <p class="col-lg-3 m-0">発売日</p> <p class="col-lg-9 m-0"><%= @book.salesDate %></p>
          <p class="col-lg-3 m-0">作品シリーズ</p> <p class="col-lg-9 m-0"><%= @book.series %></p>
          <p class="col-lg-3 m-0">所持登録数</p>  <p class="col-lg-9 m-0"><%= @book.count_subs %>人</p>
          <p class="col-lg-3 m-0">お気に入り登録数</p>  <p class="col-lg-9 m-0"><%= @book.count_favs %>人</p>
        </div>
        <div class="subscribe_book_zone_<%= @book.isbn %>">
          <%= render 'subscribes/sub_button', isbn: @book.isbn %>
        </div>
        <div class="favorite_book_zone_<%= @book.isbn %>">
          <%= render 'favorites/fav_button', isbn: @book.isbn %>
        </div>
        <div class="mt-2 mb-2">
          <%= link_to '楽天', @book.url, class: 'card-link btn-sm btn-dark ml-1', target:'blank' %>
          <% amazonurl = "http://www.amazon.co.jp/dp/#{change_isbn(@book.isbn)}" %>
          <%= link_to 'Amazon', amazonurl, class: 'card-link btn-sm btn-dark ml-1', target:'blank' %>
          <% unless @book.series.nil? %>
            <%= link_to "検索", {controller: "books", action: "new", title: @book.series, sortselect: "+releaseDate"}, class: "card-link btn-sm btn-light border ml-1" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<%= render 'reviews/review_create_button', book: @book %>

<button type="button" class="btn btn-dark" data-toggle="collapse" data-target="#collapseReview" aria-expanded="false" aria-controls="collapseReview">
  レビューをみる（下に表示されます）
</button>

<% if Book.find(@book.id).reviewuser.include?(current_user) %>
  <% review = current_user.reviews.find_by(book_id: @book.id) %>
  <div class="card m-4 border-info">
    <div class="card-header">あなたがこの漫画に投稿したレビュー</div>
    <%= render 'reviews/review_card', review: review %>
  </div>
<% end %>

<div class="collapse" id="collapseReview">
  <% @reviews = Review.where(book_id: @book.id).order(created_at: "DESC").limit(10) %>
  <% unless @reviews.empty? %>
    <% @reviews.each do |review| %>
      <%= render 'reviews/review_card', review:review %>
    <% end %>
    <p><%= link_to '全てのレビューをみる', review_index_path(@book.id) %></p>
    <% else %>
      <p>この作品にはまだレビューはありません。</p>
  <% end %>
</div>