backend/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get root to: 'toppages#index'

  resources :users, only: %i[show edit update]

  resources :subscribes, only: %i[create destroy]
  resources :favorites, only: %i[create destroy]

  get 'books', to: 'books#new'
  get 'books/:isbn', to: 'books#show', as: 'book'
  get 'books/:isbn/reviews/new', to: 'reviews#new', as: 'review_new'
  get 'subscribe-ranking', to: 'books#ranking'
  get 'review-ranking', to: 'books#review_ranking'

  get 'howto', to: 'toppages#howto'

  resources :reviews
  get 'reviews/index/:id', to: 'reviews#index', as: 'review_index'
  get 'reviews/error', to: 'reviews#error'

  resources :reviewfavorites, only: %i[create destroy]
  get 'newlys/download', to: 'newlys#download'
  get 'newlys', to: 'newlys#search'
  get 'favnews', to: 'newlys#newfav'

  # API routes
  get 'v1/ranking/subs', to: 'books#api_subs_ranking'
  get 'v1/ranking/review', to: 'books#api_review_ranking'
  get 'v1/books', to: 'books#api_new'

  namespace :v1 do
    mount_devise_token_auth_for 'User', at: 'auth', controllers: {
      confirmations:  'overrides/confirmations'
    }
  end
end

backend/app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

backend/app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

backend/app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-light bg-light">
    <a class="navbar-brand title_comicfarm_small" href="/">ComicFarm</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item"><%= link_to fa_icon("book", text: "漫画を探す"), books_path, class: 'nav-link' %></li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" role="button" id="navbarDropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fa fa-star"></i> ランキング
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to fa_icon("plus", text: "登録数ランキング"), '/subscribe-ranking', class: 'dropdown-item' %>
            <%= link_to fa_icon("thumbs-up", text: "高評価ランキング"), '/review-ranking', class: 'dropdown-item' %>
          </div>
        </li>
        <li class="nav-item"><%= link_to fa_icon("search", text: "新刊検索"), newlys_path, class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to fa_icon("bell", text: "買うかもしれない新刊"), favnews_path, class: 'nav-link' %></li>
        <% if user_signed_in? %>
          <% if current_user.admin == true && current_user.downloadadmin == true %>
            <li class="nav-item"><%= link_to fa_icon("download", text: "新刊情報登録"), newlys_download_path, class: 'nav-link' %></li>
          <% end %>
        <% end %>
        <li class="nav-item"><%= link_to fa_icon("question-circle", text: "使い方"), '/howto', class: 'nav-link' %></li>
      </ul>
      <% if user_signed_in? %>
        <ul class="navbar-nav">
          <li class="nav-item"><%= link_to fa_icon("user", text: current_user.name), user_path(current_user), class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to fa_icon("sign-out", text: "ログアウト"), destroy_user_session_path, method: :delete, class: 'nav-link' %></li>
        </ul>
      <% else %>
        <ul class="navbar-nav">
          <li class="nav-item"><%= link_to fa_icon("user-plus", text: "登録する"), new_user_registration_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to fa_icon("sign-in", text: "ログイン"), new_user_session_path, class: 'nav-link' %></li>
        </ul>
      <% end %>
    </div>
  </nav>
</header>

backend/app/views/layouts/application.html.erb
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Economica:700" rel="stylesheet">
    <title>ComicFarm</title>
  </head>
  <body>
    <div id="wrapper">
      <%= render 'layouts/navbar' %>
      <div class="container">
        <%= render 'layouts/flash_messages' %>
        <%= yield %>
      </div>
      <footer class="text-center">
        <!-- Rakuten Web Services Attribution Snippet FROM HERE -->
        <a href="https://webservice.rakuten.co.jp/" target="_blank"><img src="https://webservice.rakuten.co.jp/img/credit/200709/credit_22121.gif" border="0" alt="楽天ウェブサービスセンター" title="楽天ウェブサービスセンター" width="221" height="21"/></a>
        <!-- Rakuten Web Services Attribution Snippet TO HERE -->
        <div class="text-muted">Copyright (C) 2019 <span id="footer_comicfarm">ComicFarm</span> All Rights Reserved</div>
      </footer>
    </div>
  </body>
</html>